# 100 numpy exercises (日本語翻訳版)

<!--
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.
If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>
-->
これは、numpy のメーリングリスト、stack overflow、numpy のドキュメントで収集された演習を集めたものです。
このコレクションの目的は、昔からのユーザと新しいユーザの両方のためのクイックリファレンスを提供するだけでなく、
教える人のために練習のセットを提供することです。
エラーを見つけた場合や、より良い解法を見つけた場合は、遠慮なく、イシューをオープンしてください <https://github.com/rougier/numpy-100>

個人の趣味で翻訳しています、日本語化での誤りやコメント等は、こちらに、イシューをオープンしてください。
<https://github.com/osawat/numpy-100>

<!--
#### 1. Import the numpy package under the name `np` (★☆☆) 
-->
#### 1. numpy パッケージを `np` の名前でインポートする (★☆☆)

In [1]:
import numpy as np

<!--
#### 2. Print the numpy version and the configuration (★☆☆) 
-->
#### 2. numpy バージョンとその設定を表示する (★☆☆)

In [2]:
print(np.__version__)

1.19.5


<!--
#### 3. Create a null vector of size 10 (★☆☆) 
-->
#### 3. 大きさ 10 の零ベクトルを生成する (★☆☆)

In [3]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<!--
#### 4.  How to find the memory size of any array (★☆☆) 
-->
#### 4.  配列のメモリーサイズを知る方法は (★☆☆) 

In [4]:
zeros.nbytes

80

<!--
#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
-->
#### 5.  コマンドラインからの、numpy add 関数のドキュメントの取得方法は? (★☆☆) 

In [5]:
# TODO 
!python -c 'import numpy;numpy.info(numpy.add)' # 覚える

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

<!--
#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
-->
#### 6.  5番目の値だけ 1 の大きさ 10 の零ベクトルを生成する (★☆☆) 

In [6]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


<!--
#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
-->
#### 7.  値の範囲が 10 から 49 であるようなベクトルを生成する (★☆☆) 

In [7]:
# TODO
r = np.arange(10,50) # 覚える
print(r)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


<!--
#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
-->
#### 8.  ベクトルを逆転する (最初の要素が最後に) (★☆☆) 

In [8]:
# TODO
r2 = np.arange(50)
print(r2[::-1])




[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


<!--
#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
-->
#### 9.  値の範囲が 0 から 8 であるような 3x3 マトリクスを生成する (★☆☆) 

In [9]:
# TODO
reshap = np.arange(9).reshape((3,3)) # 覚える
print(reshap)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<!--
#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
-->
#### 10. \[1,2,0,0,4,0\] からゼロでない要素の添え字を見つける (★☆☆) 

In [10]:
n = np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4]),)


<!--
#### 11. Create a 3x3 identity matrix (★☆☆) 
-->
#### 11. 3x3 の単位行列を生成する (★☆☆) 

In [11]:
np.identity(3)




array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<!--
#### 12. Create a 3x3x3 array with random values (★☆☆) 
-->
#### 12. 乱数で 3x3x3 配列を生成する (★☆☆) 

In [12]:
np.random.rand(3,3,3)

array([[[0.12388194, 0.2413179 , 0.93532302],
        [0.08000448, 0.83767912, 0.12590358],
        [0.77580526, 0.89418084, 0.68574131]],

       [[0.78566444, 0.31225626, 0.12243363],
        [0.50963481, 0.68392165, 0.7906757 ],
        [0.12561783, 0.86238623, 0.21677767]],

       [[0.86496044, 0.66049683, 0.72123994],
        [0.46764921, 0.17443575, 0.99793598],
        [0.42939696, 0.13935891, 0.03035143]]])

<!--
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
-->
#### 13. 乱数で 10x10 配列を生成して、その最小値と最大値を見つける (★☆☆) 

In [13]:
r = np.random.rand(10,10)
print(r.min())
print(r.max())

0.017080956204918896
0.9971573713296693


<!--
#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
-->
#### 14. 大きさ 30 の乱数のベクトルを生成して、その平均を求める (★☆☆) 

In [14]:
np.random.rand(30).mean()

0.4798359473918804

<!--
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
-->
#### 15. 周囲が 1 で内部が 0 であるような2次元配列生成する (★☆☆) 

In [19]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

<!--
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
-->
#### 16. 既存の配列の周囲を 0 で囲む方法は? (★☆☆) 

<!--
#### 17. What is the result of the following expression? (★☆☆) 
-->
#### 17. 以下の式の結果は何か? (★☆☆) 

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

<!--
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
-->
#### 18. 対角成分の直下に 1,2,3,4 の成分を持つ 5x5 行列を生成する (★☆☆) 

<!--
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
-->
#### 19.  8x8 行列を生成して、市松模様で埋める (★☆☆) 

<!--
#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
-->
#### 20. shape属性が (6,7,8) の配列のとき、100 番目の要素の添え字 (x,y,z)は？

<!--
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
-->
#### 21. tile 関数を使って 8x8 の市松模様の行列を生成する (★☆☆) 


<!--
#### 22. Normalize a 5x5 random matrix (★☆☆) 
-->
#### 22. 5x5 の乱数の行列を正規化する (★☆☆) 

<!--
#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
-->
#### 23. 色を 4 個の符号なしバイト型 (RGBA) で表現するカスタム dtype を作成する (★☆☆) 

<!--
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
-->
#### 24. 5x3 行列と 3x2 行列の掛け算 (実数の行列積) (★☆☆) 

<!--
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
-->
#### 25. 1次元配列が与えられたとき、３番目から８番目の全要素をネゲート(負値)する (★☆☆) 

<!--
#### 26. What is the output of the following script? (★☆☆) 
-->
#### 26. 以下のスクリプトの出力は? (★☆☆) 

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

<!--
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
-->
#### 27. Z が整数型のベクトルのとき、これらの式のどれが適切か？ (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

<!--
#### 28. What are the result of the following expressions?
-->
#### 28. 以下の式の結果は何か?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

<!--
#### 29. How to round away from zero a float array ? (★☆☆) 
-->
#### 29. ゼロから遠くなるように浮動小数点型の配列の小数点を丸める方法は? (★☆☆) 

<!--
#### 30. How to find common values between two arrays? (★☆☆) 
-->
#### 30. 2つの配列に共通する値の見つけ方は? (★☆☆) 

<!--
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
-->
#### 31. すべての numpy の警告を無視する方法は (非推奨)? (★☆☆) 

<!--
#### 32. Is the following expressions true? (★☆☆) 
-->
#### 32. 以下の式は正しいですか? (★☆☆) 

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

<!--
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
-->
#### 33. 昨日、今日、明日の日付の取得方法は? (★☆☆) 

<!--
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
-->
#### 34. 2016年7月のすべての日付の取得方法は? (★★☆) 


<!--
#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
-->
#### 35. ((A+B)\*(-A/2)) の計算方法は (copyせずに)? (★★☆) 

<!--
#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
-->
#### 36. 乱数の配列から整数部分を抽出する5種類の方法は (★★☆) 

<!--
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
-->
#### 37. 行の値が 0 から 4 の 5x5 行列を生成する (★★☆) 

<!--
#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
-->
#### 38. 10個の整数を生成するジェネレータ関数があるとき、それを使って配列を生成する (★☆☆) 

<!--
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
-->
#### 39. 0 から 1 の範囲の値を持つ大きさ 10 のベクトルを生成する (ただし、両端の 0 と 1 は含めない) (★★☆) 

<!--
#### 40. Create a random vector of size 10 and sort it (★★☆) 
-->
#### 40. 大きさが 10 の乱数を生成して、それを並びかえる (★★☆) 

<!--
#### 41. How to sum a small array faster than np.sum? (★★☆) 
-->
#### 41. np.sumより高速に小さい配列を集計する方法は? (★★☆) 

<!--
#### 42. Consider two random array A and B, check if they are equal (★★☆) 
-->
#### 42. A と B の2つの乱数配列があるとき、それらが等しいかをチェックする (★★☆) 

<!--
#### 43. Make an array immutable (read-only) (★★☆) 
-->
#### 43. イミュータブル(読み取り専用)の配列を生成する (★★☆) 

<!--
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
-->
#### 44. 直交座標で 10x2 行列があるとき、それらを極座標に変換する (★★☆) 

<!--
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
-->
#### 45. 大きさ 10 の乱数のベクトルを生成して、その最大値を 0 に置き換える (★★☆) 

<!--
#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
-->
#### 46. \[0,1\]x\[0,1\] 領域を網羅する `x` 座標と `y` 座標を持つ構造化配列を生成する (★★☆) 

<!--
####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
-->
####  47. 2つの配列 X と Y が与えられたとき、コーシー行列 C (Cij =1/(xi - yj)) を作成する 

<!--
#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
-->
#### 48. numpy スカラー型のそれぞれについて、表現可能な最小値と最大値を表示する (★★☆) 

<!--
#### 49. How to print all the values of an array? (★★☆) 
-->
#### 49. 配列のすべての値を表示する方法は? (★★☆) 

<!--
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
-->
#### 50. ベクトルの中で指定したスカラーに最も近い値を見つける方法は? (★★☆) 

<!--
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
-->
#### 51. 位置 (x,y) と 色 (r,g,b) を表現する構造化配列を生成する (★★☆) 

<!--
#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
-->
#### 52. shape属性が (100,2) の座標を表現する乱数のベクトルがあるとき、各点ごとの距離を求める (★★☆) 

<!--
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
-->
#### 53. 浮動小数点 (32 bits) 配列を整数型 (32 bits) 配列に変換する方法は? 

<!--
#### 54. How to read the following file? (★★☆) 
-->
#### 54. 以下のファイルを読む方法は? (★★☆) 

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

<!--
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
-->
#### 55. numpy 配列で enumerate に相当するものは何ですか?

<!--
#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
-->
#### 56. 一般的な2次元正規分布の配列を生成する (★★☆) 

<!--
#### 57. How to randomly place p elements in a 2D array? (★★☆) 
-->
#### 57. 2次元配列中に p 個の要素をランダムに配置する方法は? (★★☆) 

<!--
#### 58. Subtract the mean of each row of a matrix (★★☆) 
-->
#### 58. 行列の各行からその平均を減算する (★★☆) 

<!--
#### 59. How to sort an array by the nth column? (★★☆) 
-->
#### 59. 配列を n 番目の列でソートする方法は? (★★☆) 

<!--
#### 60. How to tell if a given 2D array has null columns? (★★☆) 
-->
#### 60. 与えられた2次元配列に null の列があるかを調べる方法は? (★★☆) 

<!--
#### 61. Find the nearest value from a given value in an array (★★☆) 
-->
#### 61.  与えられた値から最も近い値を配列の中に見つける (★★☆) 

<!--
#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
-->
#### 62. shape属性が (1,3) と (3,1) の2つの配列があるとき、イテレータを使ってその和を計算する方法は? (★★☆) 

<!--
#### 63. Create an array class that has a name attribute (★★☆) 
-->
#### 63. name属性を持つ配列クラスを作成する (★★☆) 

<!--
#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
-->
#### 64. あるベクトルが与えられたとき、第2のベクトルにより添え字指定されたそれぞれの要素に 1 を加える方法は (添え字は繰り返されることに注意)? (★★★) 

<!--
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
-->
#### 65. 添え字リスト (I) に基づきベクトル (X) の要素を配列 (F) に累積する方法は? (★★★) 

<!--
#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
-->
#### 66. 画像が (w, h, 3) (dtype=ubyte) のとき、ユニークな色の数を計算する(★★★) 

<!--
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
-->
#### 67. 4次元配列のとき、一気に最後の2軸で合計する方法は? (★★★) 

<!--
#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★) 
-->
#### 68. 1次元ベクトル D を考えたとき、部分集合を添え字で記述する同じサイズのベクトル S を使用して、D の部分集合の平均を計算する方法は？

<!--
#### 69. How to get the diagonal of a dot product? (★★★) 
-->
#### 69. ドット積の対角要素を取得する方法は? (★★★) 

<!--
#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
-->
#### 70. ベクトル \[1, 2, 3, 4, 5\] があるとき、それぞれの値の間に連続する3つのゼロをはさむ新しいベクトルを生成する方法は? (★★★) 

<!--
#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
-->
#### 71. (5,5,3) 次元の配列があるとき、それに (5,5) 次元の配列を掛ける方法は? (★★★) 

<!--
#### 72. How to swap two rows of an array? (★★★) 
-->
#### 72. 配列の2つの行を交換する方法は? (★★★) 

<!--
#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
-->
#### 73. 10個の三角形を記述する10個の三つ組みがあるとき (共有された頂点を持つ) 、すべての三角形を構成するユニークな線分の集合を見つける (★★★) 

<!--
#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
-->
#### 74. bincountで与えられる配列 C があるとき、np.bincount(A) == C であるような配列 A の生成方法は? (★★★) 

<!--
#### 75. How to compute averages using a sliding window over an array? (★★★) 
-->
#### 75. 配列にスライドウィンドウを使って平均を計算する方法は? (★★★) 

<!--
#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
-->
#### 76. 1次元の配列 Z があるとき、最初の行が (Z\[0\],Z\[1\],Z\[2\]) で、それに続く行はそれぞれ 1 だけシフトされた2次元配列を生成する (最後の行は、(Z\[-3\],Z\[-2\],Z\[-1\]) になる) (★★★) 

<!--
#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
-->
#### 77. ブール値を否定する方法、また、浮動小数点の符号を変更する方法は? (★★★) 

<!--
#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)
-->
#### 78. 直線 (2次元) を記述する2組の点 P0、P1そして点 p があるとき、点 p から直線 i (P0\[i\],P1\[i\]) までの距離を計算する方法は? (★★★)

<!--
#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)
-->
#### 79. 直線 (2次元) を記述する2組の点 P0、P1 そして1組の点 P があるとき、それぞれの点 (P\[j\]) から各線 i (P0\[i\],P1\[i\]) までの距離を計算する方法は? (★★★)

<!--
#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
-->
#### 80. 任意の配列に対して、定められたshape属性で、指定された要素が中央に配置されるような一部分を抽出する関数を書く（必要に応じて `fill` 値でパディング） (★★★) 

<!--
#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
-->
#### 81. 配列 Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\] があるとき、配列 R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\] の生成方法は? (★★★) 

<!--
#### 82. Compute a matrix rank (★★★) 
-->
#### 82. 行列のランク計算 (★★★) 

<!--
#### 83. How to find the most frequent value in an array? 
-->
#### 83. 配列の中での最頻値の求め方は? 

<!--
#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
-->
#### 84. 10x10 の乱数の行列から隣接するすべての 3x3 ブロックを抽出する (★★★) 

<!--
#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
-->
#### 85. Z\[i,j\] == Z\[j,i\] となるような2次元配列のサブクラスを作成する (★★★) 

<!--
#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
-->
#### 86. p 個の shape属性 (n,n) の行列と p 個の shape属性 (n,1) のベクトルがあるとき、一度に p 個の行列積の総和を計算する方法は? (結果は shape属性が (n,1)) (★★★) 

<!--
#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
-->
#### 87. 16x16 の配列があるとき、ブロック合計 (ブロック・サイズは 4x4 ) の取得方法は? (★★★) 

<!--
#### 88. How to implement the Game of Life using numpy arrays? (★★★)
-->
#### 88. numpy 配列を使ったライフゲームの実装方法は? (★★★)

<!--
#### 89. How to get the n largest values of an array (★★★) 
-->
#### 89. 配列の n 個の最大値の取得方法は (★★★) 

<!--
#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
-->
#### 90. 任意の数のベクトルがあるとき、そのデカルト積を生成する (すべての要素のすべての組み合わせ) (★★★) 

<!--
#### 91. How to create a record array from a regular array? (★★★) 
-->
#### 91. 普通の配列からレコード配列の生成方法は? (★★★) 

<!--
#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
-->
#### 92. 大きなベクトル Z があるとき、異なる3つの方法で Z の3乗を計算する (★★★) 

<!--
#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
-->
#### 93. ２つの配列 A と Ｂ、shape属性 (8,3) と (2,2) があるとき、B の要素の順序によらず、B の各行の要素を含む A の行を見つける方法は？ (★★★) 

<!--
#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)
-->
#### 94. 10x3 行列があるとき、等しくない値を持つ行を抽出する (例 \[2,2,3\]) (★★★)

<!--
#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
-->
#### 95. 整数型のベクトルを2進数表示の行列に変換する (★★★) 

<!--
#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
-->
#### 96. 2次元配列が与えられたとき、ユニークな行を抽出する方法は? (★★★) 

<!--
#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
-->
#### 97. 2つのベクトル A と B があるとき、内積、外積、総和、掛け算の関数をアインシュタイン縮約記法で書く (★★★) 

<!--
#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
-->
#### 98. 2つのベクトル (X,Y) によって記述される経路を考えたとき、等距離間隔でサンプリングする方法は (★★★)? 

<!--
#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
-->
#### 99. 整数 n および2次元配列 X が与えられたとき、n 項の多項分布から導かれたと解釈できる行を配列 X から選ぶ　(つまり、行は整数のみを含み、その合計は n のもの) (★★★) 

<!--
#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
-->
#### 100. 1次元配列 X の平均に対してブートストラップ95％信頼区間を計算する (すなわち、N 回の復元抽出で配列の要素を再サンプリングし、それぞれサンプルの平均を計算し、平均値に対するパーセンタイルを計算する) (★★★) 